server:
  port: 8091
spring:
  application:
    name: produce-server
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server1:8081/eureka/, http://eureka-server2:8082/eureka/, http://eureka-server3:8083/eureka/
