#spring配置
spring:
#  profiles: application-eureka-server1
  application:
    #应用名称
    name: eureka-server

#服务器配置
server:
  #端口
  port: 8081

#服务中心发现注册配置
eureka:
  instance:
    #主机名称
    hostname: eureka-server1
    appname: eureka-server
  client:
    #服务注册中心地址
    service-url:
      defaultZone:  http://eureka-server2:8082/eureka,http://eureka-server3:8083/eureka
    #服务注册中心相互注册一定要显示的设置register-with-eureka 和fetch-registry的值为true,否则会服务不可用
    register-with-eureka: true
    fetch-registry: true