server:
  port: 9992
  spring:
    datasource:
      url: jdbc:mysql://www.iamcrawler.cn:3306/goddess?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=UTC
      username: root
      password: 123456
      driver-class-name:  com.mysql.jdbc.Driver
    redis:
      host: www.iamcrawler.cn
      port: 6379
      password:
      database: 0
    application:
      name: crawler-auth
    eureka:
      client:
        service-url:
          defaultZone: http://localhost:9990/eureka/
    management:
      endpoints:
        web:
          exposure:
            include: health,info,loggers